kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluster1
  annotations:
        volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
        - ReadWriteMany
  resources:
        requests:
          storage: 2Gi
